### PR TITLE
feat: support customize model name #50

### LINKED ISSUE #50: support custom model name
image

my model not in CompletionModel enum, so i need to set the model name by String

### PR DESCRIPTION
**Pull request by shirayner**
feat: support customize model name

### CODE REVIEW

**Comment by qianmoQ** [comment]
@shirayner 
Thank you for your contribution. You are required to deal with the style issues of the code before merging.

```java
openai-java-sdk/src/main/java/org/devlive/sdk/openai/OpenAiClient.java:186: Multiple consecutive blank lines [RegexpMultiline]
openai-java-sdk/src/main/java/org/devlive/sdk/openai/entity/ChatEntity.java:102:54: '{' at column 54 should be on a new line. [LeftCurly]
openai-java-sdk/src/main/java/org/devlive/sdk/openai/entity/ChatEntity.java:119:15: 'if' is not followed by whitespace. [WhitespaceAround]
openai-java-sdk/src/main/java/org/devlive/sdk/openai/entity/ChatEntity.java:119:48: '{' is not preceded with whitespace. [WhitespaceAround]
openai-java-sdk/src/main/java/org/devlive/sdk/openai/entity/ChatEntity.java:122:13: '}' at column 13 should be alone on a line. [RightCurly]
openai-java-sdk/src/main/java/org/devlive/sdk/openai/entity/ChatEntity.java:122:14: 'else' is not preceded with whitespace. [WhitespaceAround]
```

**Comment by shirayner** [comment]
I fixed the style error, please help me to approve it

**Comment by qianmoQ** [comment]
> I fixed the style error, please help me to approve it

```java
openai-java-sdk/src/main/java/org/devlive/sdk/common/DefaultClient.java:83:9: '}' at column 9 should be alone on a line. [RightCurly]
openai-java-sdk/src/main/java/org/devlive/sdk/common/DefaultClient.java:113:9: '}' at column 9 should be alone on a line. [RightCurly]
openai-java-sdk/src/main/java/org/devlive/sdk/common/DefaultClient.java:385:9: '}' at column 9 should be alone on a line. [RightCurly]
openai-java-sdk/src/main/java/org/devlive/sdk/openai/entity/ChatEntity.java:123:13: '}' at column 13 should be alone on a line. [RightCurly]
```

**Comment by shirayner** [comment]
please help me to approve it again

**Comment by qianmoQ** [comment]
Thank you for your contribution

**Pull request merged**
